language: cpp

before_install: sudo apt install mesa-common-dev libglfw-dev libsdl2-dev libsdl2-mixer-dev libxrandr-dev libxi-dev 

script: make && make test

os:
- linux
- osx

sudo: false
dist: trusty

